server:
  port: 8082
  servlet:
    context-path: /monitoramento

spring:
  application:
    name: monitoramento
  data:
    mongodb:
#      authentication-database: imagens
#      username: monitoramento
#      password: monitoramento
#      database: imagens
#      port: 27017
#      host: localhost
      uri: mongodb+srv://monitoramento:monitoramento@cluster-tcc.26f15.mongodb.net/imagens

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      ##defaultZone: http://localhost:8761/registry/eureka
      defaultZone: http://tcc-discovery.herokuapp.com/registry/eureka/
      
